# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

python:
 - "3.6.1"
 - "3.8"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
 - "pip install --upgrade pip"
 - "pip install -r requirements.txt"
 - "pip install ."
 - "git config --global user.email \"travis-user@example.com\""
 - "git config --global user.name \"Travis Userq\""
# - "echo \"[MASTER]\" > .pylintrc"
# - "echo \"disable=locally-disabled,locally-enabled\" >> .pylintrc"

# command to run tests, e.g. python setup.py test
# script: tox
script:
 - py.test -vv --tb short

# branches
branches:
  only:
  - /^\d+\.\d+\.\d+$/
  - travis
